---
#Provision some instances:
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
  - group_vars/all
 
  tasks:
  - name: Launch research instances
    ec2: >
     access_key="{{ ec2_access_key }}"
     secret_key="{{ ec2_secret_key }}"
     keypair="{{ ec2_keypair }}"
     group="{{ ec2_security_group }}"
     type="{{ ec2_instance_type }}"
     image="{{ ec2_image }}"
     region="{{ ec2_region }}"
     instance_tags="{'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'notting-deployment-{{project_name}}'}"
     count="{{ research_count }}"
     wait=true
    register: ec2

  - name: Wait for instances to boot
    local_action: pause seconds=60

  - name: Wait for SSH to come up
    local_action: wait_for host={{ item.public_dns_name }}
      port=22 timeout=60 state=started
    with_items:
      - "{{ ec2.instances }}"
